### ISSUE TITLE
How do I select the initial polynomial

### ISSUE THREAD

**Issue by zorce** [niccokunzmann/crc8#1]
Need to be able to set different crc8 polynomial for the crc calculation.

**Comment by niccokunzmann** [comment]
Great idea, I did not know this is a use case. Would you like to write
the code for this? I will merge and upload.

**Comment by niccokunzmann** [comment]
Would https://github.com/ryanfpage/crc8/pull/1 be what you expect?

**Comment by niccokunzmann** [comment]
This should be solved by #4

**Comment by niccokunzmann** [comment]
Please comment if this is not the case. I assume it is and as such close this issue.
