### ISSUE TITLE
Request: return self in update() and reset() methods

### ISSUE THREAD

**Issue by roger-** [niccokunzmann/crc8#11]
Not sure how closely you want to follow hashlib, but this would allow one-liners like: 

```
result = hash.reset().update(data).digest()
```

<small>
<hr/>
We're using <a href="https://polar.sh/niccokunzmann">Polar.sh</a> so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/crc8/issues/11">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/crc8/issues/11/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/crc8/issues/11/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
Hi, that is surely possible. Please create a pull request if you like to have this!

**Comment by roger-** [comment]
Done: #12

**Comment by niccokunzmann** [comment]
This is published as v0.2.1
