### ISSUE TITLE
What polynomial does this library use?

### ISSUE THREAD

**Issue by dlmoffett** [niccokunzmann/crc8#2]
Sorry if this is a dumb question, but I took a quick glance at the source and it wasn't obvious to me what polynomial was being used, nor was this info in the readme. It looked like, perhaps, a pre-generated lookup table was being used.

**Comment by dlmoffett** [comment]
Simple comparison with other tools is showing that this library uses CRC-8-CCITT:

x^8 + x^2 + x + 1

or 

0x07

**Comment by niccokunzmann** [comment]
Would you like to document this?
