### ISSUE TITLE
Settings clarification requests

### ISSUE THREAD

**Issue by gaetano83** [niccokunzmann/crc8#6]
Hi,
Thank you for the module.

Using this module, I would like to match the calculation of CRC8 from this website http://www.sunshine2k.de/coding/javascript/crc/crc_js.html when:
- Polynomial = 0x7
- Initial value = 0xFF
- Final Xor Value = 0x0

Which settings I have to use with crc8 module.

Thanks

![image](https://user-images.githubusercontent.com/8738064/78421701-f9014b80-7659-11ea-950d-efa2d8a05898.png)

**Comment by niccokunzmann** [comment]
This is a good question. Please have a look at the JS implementation of the website.

**Comment by niccokunzmann** [comment]
![image](https://github.com/niccokunzmann/crc8/assets/564768/2dcdab60-bc6b-430c-addf-f1afe9472c14)

```
>>> h = crc8.crc8()
>>> h.update(b'hello')
>>> h.hexdigest()
'92'
```

**Comment by niccokunzmann** [comment]
I will close this - you can open it again.
