### ISSUE TITLE
Missing a reset method

### ISSUE THREAD

**Issue by henriksod** [niccokunzmann/crc8#8]
This crc8 lib is missing a reset method to restore `self._sum` to its initial state.

I want to retain the same `CRC8` object between incoming data packets while calculating the crc8 value for each individual packet without explicitly setting `crc8._sum = initial_start_value`.

**Comment by niccokunzmann** [comment]
I think, to close this, I want a docstring on reset(). Nice to have is an example in the README.

**Comment by henriksod** [comment]
#10

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by niccokunzmann** [comment]
This is in version v0.2.0. Thanks again!
